# -*- coding: utf-8 -*-
"""RPGpt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OrYtNh6pa8GJvJkNivJYGy2yAodcZxOq
"""

import time

def intro():
    print("Você é um aventureiro corajoso em busca de um tesouro lendário!")
    print("Você chegou a uma encruzilhada. Você deseja ir para a direita ou para a esquerda?")
    escolha = input("Digite 'direita' ou 'esquerda': ")

    if escolha.lower() == "direita":
        caminho_direita()
    elif escolha.lower() == "esquerda":
        caminho_esquerda()
    else:
        print("Opção inválida!")
        intro()

def caminho_direita():
    print("Você escolheu o caminho da direita.")
    print("Você se depara com um rio. O que você gostaria de fazer?")
    escolha = input("Digite 'atravessar' ou 'voltar': ")

    if escolha.lower() == "atravessar":
        print("Você tenta atravessar o rio nadando.")
        time.sleep(1)
        print("Oh não! O rio está cheio de piranhas famintas. Você foi devorado.")
        game_over()
    elif escolha.lower() == "voltar":
        print("Você decide voltar e escolher outro caminho.")
        time.sleep(1)
        intro()
    else:
        print("Opção inválida!")
        caminho_direita()

def caminho_esquerda():
    print("Você escolheu o caminho da esquerda.")
    print("Você se depara com uma caverna escura. O que você gostaria de fazer?")
    escolha = input("Digite 'entrar' ou 'voltar': ")

    if escolha.lower() == "entrar":
        print("Você entra na caverna e encontra um baú brilhante!")
        time.sleep(1)
        print("Você abre o baú e encontra um tesouro valioso! Parabéns, você venceu!")
    elif escolha.lower() == "voltar":
        print("Você decide voltar e escolher outro caminho.")
        time.sleep(1)
        intro()
    else:
        print("Opção inválida!")
        caminho_esquerda()

def game_over():
    print("Fim de jogo! Deseja jogar novamente?")
    escolha = input("Digite 'sim' ou 'não': ")

    if escolha.lower() == "sim":
        intro()
    elif escolha.lower() == "não":
        print("Obrigado por jogar! Até a próxima.")
    else:
        print("Opção inválida!")
        game_over()

# Início do jogo
intro()

#rascunhos descartados]
te = int(input('quantos turnos do inimigo? '))
tp = int(input('quantos turnos do player? '))

'''def ataques_enemy():
  for i in range(te):
    dano_no_player(int(choices(danoE, Eprob)[0]))
    i=i+1
    if i==te and vida>0:
      print("Apenas um leve ferimento B>!! Kk")'''

'''def ataques_player():
  for i in range(tp):
    dano_no_enemy(int(choices(danoP, Pprob)[0]))
    i=i+1
    if i==tp and vidaE>0:
      print("Não tema, pois mesmo que sua morte ainda não tenha chegado, eu não descansarei até te exterminar, pois eu sou o grande e magnífico protagonista.")'''